baseURL = "https://briefsteller.de/"
languageCode = "de"
title = "Briefsteller"
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
theme = ["projektemacher-base"]
paginate = 8
Copyright = "Projektemacher"

# navigation
[menu]
    [[menu.main]]
        name = "Neueste Beiträge"
        URL = "/post"
        weight = 1

    [[menu.main]]
        name = "Über"
        URL = "/about"
        weight = 2

[markup.goldmark.renderer]
  unsafe= true

[imaging]
    quality = 95

[outputs]
    page = ["HTML", "JSON"]

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"
