baseURL = "https://briefsteller.de/"
languageCode = "de"
title = "Briefsteller"
languagecode = "de"
defaultcontentlanguage = "de"
publishDir = "docs"
canonifyurls = true
disablePathToLower = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
theme = ["projektemacher-base"]
#paginate = 8
Copyright = "Projektemacher"
enableGitInfo = true

[pagination]
  pagerSize = 8

# navigation
[menu]
    [[menu.main]]
        name = "Neueste Beiträge"
        URL = "/post"
        weight = 1

    [[menu.main]]
        name = "Über"
        URL = "/about"
        weight = 2

[mediaTypes]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]
  [mediaTypes."image/jxl"]
    suffixes = ["jxl"]

[outputFormats]
  [outputFormats.iiif]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.iiif-manifest]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.iiif-collection]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "collection"
    notAlternative = true

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        #typographer = true
        attribute = true
        strikethrough = true

    [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.insert]
            enable = true
        [markup.goldmark.extensions.extras.mark]
            enable = true
        [markup.goldmark.extensions.extras.subscript]
            enable = true
        [markup.goldmark.extensions.extras.superscript]
            enable = true

  [markup.goldmark.extensions.typographer]
          apostrophe = '&rsquo;'
          disable = false
          ellipsis = '&hellip;'
          emDash = '&mdash;'
          enDash = '&ndash;'
          leftAngleQuote = '&laquo;'
          leftDoubleQuote = '&ldquo;'
          leftSingleQuote = '&lsquo;'
          rightAngleQuote = '&raquo;'
          rightDoubleQuote = '&rdquo;'
          rightSingleQuote = '&rsquo;'

[imaging]
    quality = 95

[outputs]
    page = ["HTML", "JSON"]

[sitemap]
  changeFreq = 'weekly'

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

[build]
  writeStats = true
