name: Publish on GitHub pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 23 1 * 6'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUGO_VERSION: 0.145.0
  DEPENDENCY_MANAGER: yarn

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install required dependencies
        run: |
          ./scripts/github-setup.sh

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Create IIIF derivates
# UID is als available via $(id -u)
        run: |
          echo "Running as ${UID}"
          docker run -e CHOWN_UID=${UID} -e URL_PREFIX="https://static.projektemacher.org/briefsteller/" -v ${PWD}:${PWD} ghcr.io/cmahnke/iiif-action:latest-jxl-uploader sh -c "cd ${PWD} && ./scripts/iiif.sh"

      - name: Generate Files
        env:
          SKIP_IIIF: yes
        run: |
          ./scripts/setup.sh

      - name: Generate stats
        run: |
          ./themes/projektemacher-base/scripts/stat.sh

      - name: Build Hugo site
        run: hugo --printI18nWarnings --printUnusedTemplates

      - name: Validate JSON
        env:
          OSTYPE: linux
        run: |
          yarn run validate

      - name: Puppeteer
        run: ./themes/projektemacher-base/scripts/github/check-js-errors.sh

      - name: Cleanup disk
        run: |
          df -h
          docker rmi -f ghcr.io/cmahnke/iiif-action:latest-jxl-uploader
          rm -rf node_modules
          rm -rf content
          df -h

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
